/** Shape of public/data/cases.json — generated by scripts/prepare_assets.py. */

export type MediaKind =
  | 'bev'
  | 'rgb'
  | 'surround_sixup'
  | 'hdmap_condition'
  | 'trajectory'
  | 'map'
  | 'figure'
  | 'image';

export interface MediaItem {
  kind: MediaKind;
  label: string;
  /** Relative to the Vite base. Never absolute. */
  src: string;
  poster?: string;
  width?: number;
  height?: number;
  fps?: number;
  duration?: number;
  bytes?: number;
  sha256?: string;
  attribution?: string;
}

export interface CaseEntry {
  id: string;
  title: string;
  source: string;
  summary: string;
  tags?: string[];
  paperPanel?: string;
  media: MediaItem[];
}

export interface CasesManifest {
  manifest_version: string;
  generated_utc: string | null;
  attributions: string[];
  cases: CaseEntry[];
  /** Paper-matched surround-view clip shown above the framework section. */
  teaser?: { media: MediaItem };
  /** Framework overview figure (paper Fig. 1). */
  framework?: { media: MediaItem };
}

/** How each media kind is described in the UI. Generated vs. input must stay distinct. */
export const MEDIA_KIND_INFO: Record<MediaKind, { badge: string; note?: string }> = {
  bev: { badge: 'Bird’s-eye reconstruction' },
  rgb: { badge: 'Generated sensor video' },
  surround_sixup: {
    badge: 'Surround view',
    note: 'Six synchronized views composited into a grid for display.',
  },
  hdmap_condition: {
    badge: 'HD-map conditioning input',
    note: 'Rendering input, not generated imagery.',
  },
  trajectory: { badge: 'Trajectory' },
  map: { badge: 'Road network' },
  figure: { badge: 'Figure' },
  image: { badge: 'Image' },
};

export const isVideo = (src: string) => /\.(mp4|webm)$/i.test(src);
